name: coloring_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0 # For loading SVG assets
  path_provider: ^2.1.5 # To get app document directory for Hive
  hive: ^2.2.3 # For local NoSQL database
  hive_flutter: ^1.1.0 # Flutter integration for Hive
  path_drawing: ^1.0.1 # For parsing SVG path strings to ui.Path (if needed)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
